# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: VueJS CI

on:
  push:
    tags: "*"
    branches: "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - name: Install and build
      working-directory: ./client
      run: |
        npm ci
        npm run build --if-present
    - name: Run linter
      working-directory: ./client
      run: npm run lint
      continue-on-error: true
    - name: Run typecheck
      working-directory: ./client
      run: npm run type-check
      continue-on-error: true